version: '3.8'
services:
  stats-client:
    build: statistic/statistic-client
    image: stats-server-client
    container_name: ewn-statistic-client
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
    environment:
      - STAT-SERVER-URL=http://server:9090
      #- TZ=Europe/Moscow

  stats-server:
    restart: on-failure
    build: statistic/statistic-server
    image: stats-server-image
    container_name: ewm-stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:15.1-alpine
    container_name: EWM-stats-db
    ports:
      - "6541:5432"
    volumes:
      - /EWM-stats-db
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
